### ISSUE TITLE
Punch is (finally) broken

### ISSUE THREAD

**Issue by valentine** [hackerspacesg/hackerspace.sg#177]
```
9:42:31 PM: Build ready to start
9:42:31 PM: ---------------------------------------------------------------------DEPRECATION NOTICE: Builds using the Trusty build image will fail after September 19, 2021The build image for this site uses Ubuntu 14.04 Trusty Tahr, which is no longer supported.All Netlify builds using the Trusty build image will begin failing in the week of September 19.To avoid service disruption, please select a newer build image at the following link:https://app.netlify.com/sites/hsg/settings/deploys#build-image-selectionFor more details, visit the build image migration guide:https://answers.netlify.com/t/end-of-support-for-trusty-build-image-everything-you-need-to-know/39004---------------------------------------------------------------------
9:42:32 PM: build-image version: 8e315e54bc4032a32e73290be556cde4f8348c12
9:42:32 PM: build-image tag: v2.8.2
9:42:32 PM: buildbot version: 76af94f42647b2019c5925a515cc8332b4883b85
9:42:32 PM: No cache source specified, skip fetching cache
9:42:32 PM: Starting to prepare the repo for build
9:42:33 PM: No cached dependencies found. Cloning fresh repo
9:42:33 PM: git clone git@github.com:hackerspacesg/hackerspace.sg
9:42:34 PM: Preparing Git Reference refs/heads/master
9:42:34 PM: Starting build script
9:42:34 PM: Installing dependencies
9:42:35 PM: Downloading and installing node v6.17.1...
9:42:35 PM: Downloading https://nodejs.org/dist/v6.17.1/node-v6.17.1-linux-x64.tar.xz...
9:42:36 PM: 
###################
9:42:36 PM:                                           27.4%
9:42:36 PM: 
###############################
9:42:36 PM: ######################################### 100.0%
9:42:36 PM: Computing checksum with sha256sum
9:42:36 PM: Checksums matched!
9:42:38 PM: Now using node v6.17.1 (npm v3.10.10)
9:42:38 PM: Attempting ruby version 2.3.6, read from environment
9:42:39 PM: Using ruby version 2.3.6
9:42:39 PM: Using PHP version 5.6
9:42:39 PM: Started restoring cached node modules
9:42:39 PM: Finished restoring cached node modules
9:42:40 PM: Installing NPM modules using NPM version 3.10.10
9:42:41 PM: npm
9:42:41 PM:  WARN
9:42:41 PM:  deprecated request@2.40.0: request has been deprecated, see https://github.com/request/request/issues/3142
9:42:42 PM: npm WARN
9:42:42 PM: deprecated node-uuid@1.4.8: Use uuid module instead
9:42:42 PM: npm
9:42:42 PM: WARN deprecated hawk@1.1.1: This module moved to @hapi/hawk. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
9:42:42 PM: npm WARN deprecated boom@0.4.2: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
9:42:42 PM: npm WARN deprecated hoek@0.9.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
9:42:42 PM: npm WARN deprecated sntp@0.2.4: This module moved to @hapi/sntp. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
9:42:42 PM: npm WARN deprecated cryptiles@0.2.2: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
9:42:43 PM: npm WARN
9:42:43 PM:  deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
9:42:43 PM: npm
9:42:43 PM: WARN
9:42:43 PM:  deprecated connect@2.21.1: connect 2.x series is deprecated
9:42:46 PM: npm WARN deprecated scmp@0.0.3: scmp v2 uses improved core crypto comparison since Node v6.6.0
9:42:46 PM: npm WARN
9:42:46 PM: deprecated native-or-bluebird@1.1.2: 'native-or-bluebird' is deprecated. Please use 'any-promise' instead.
9:42:53 PM: hackerspacesg@0.0.1 /opt/build/repo
9:42:53 PM: ├─┬ ical@0.3.1
9:42:53 PM: │ ├─┬ request@2.40.0
9:42:53 PM: │ │ ├── aws-sign2@0.5.0
9:42:53 PM: │ │ ├── forever-agent@0.5.2
9:42:53 PM: │ │ ├─┬ form-data@0.1.4
9:42:53 PM: │ │ │ ├── async@0.9.2
9:42:53 PM: │ │ │ └─┬ combined-stream@0.0.7
9:42:53 PM: │ │ │   └── delayed-stream@0.0.5
9:42:53 PM: │ │ ├─┬ hawk@1.1.1
9:42:53 PM: │ │ │ ├── boom@0.4.2
9:42:53 PM: │ │ │ ├── cryptiles@0.2.2
9:42:53 PM: │ │ │ ├── hoek@0.9.1
9:42:53 PM: │ │ │ └── sntp@0.2.4
9:42:53 PM: │ │ ├─┬ http-signature@0.10.1
9:42:53 PM: │ │ │ ├── asn1@0.1.11
9:42:53 PM: │ │ │ ├── assert-plus@0.1.5
9:42:53 PM: │ │ │ └── ctype@0.5.3
9:42:53 PM: │ │ ├── json-stringify-safe@5.0.1
9:42:53 PM: │ │ ├── mime-types@1.0.2
9:42:53 PM: │ │ ├── node-uuid@1.4.8
9:42:53 PM: │ │ ├── oauth-sign@0.3.0
9:42:53 PM: │ │ ├── qs@1.0.2
9:42:53 PM: │ │ ├── stringstream@0.0.6
9:42:53 PM: │ │ ├─┬ tough-cookie@4.0.0
9:42:53 PM: │ │ │ ├── psl@1.8.0
9:42:53 PM: │ │ │ ├── punycode@2.1.1
9:42:53 PM: │ │ │ └── universalify@0.1.2
9:42:53 PM: │ │ └── tunnel-agent@0.4.3
9:42:53 PM: │ └── rrule@2.0.0
9:42:53 PM: └─┬ punch@0.5.46
9:42:53 PM:   ├── coffee-script@1.12.7
9:42:53 PM:   ├─┬ connect@2.21.1
9:42:53 PM:   │ ├── basic-auth-connect@1.0.0
9:42:53 PM:   │ ├─┬ body-parser@1.4.3
9:42:53 PM:   │ │ ├── iconv-lite@0.4.3
9:42:53 PM:   │ │ ├── qs@0.6.6
9:42:53 PM:   │ │ ├── raw-body@1.2.2
9:42:53 PM:   │ │ └─┬ type-is@1.3.1
9:42:53 PM:   │ │   └── mime-types@1.0.0
9:42:53 PM:   │ ├── bytes@1.0.0
9:42:53 PM:   │ ├─┬ compression@1.0.11
9:42:53 PM:   │ │ ├─┬ accepts@1.0.7
9:42:53 PM:   │ │ │ └── negotiator@0.4.7
9:42:53 PM:   │ │ ├── compressible@1.1.1
9:42:53 PM:   │ │ ├── debug@1.0.4
9:42:53 PM:   │ │ ├── on-headers@1.0.2
9:42:53 PM:   │ │ └── vary@1.0.1
9:42:53 PM:   │ ├── connect-timeout@1.1.1
9:42:53 PM:   │ ├── cookie@0.1.2
9:42:53 PM:   │ ├── cookie-parser@1.3.2
9:42:53 PM:   │ ├── cookie-signature@1.0.4
9:42:53 PM:   │ ├─┬ csurf@1.2.2
9:42:53 PM:   │ │ └─┬ csrf-tokens@2.0.0
9:42:53 PM:   │ │   ├── base64-url@1.3.3
9:42:53 PM:   │ │   ├── rndm@1.2.0
9:42:53 PM:   │ │   ├── scmp@0.0.3
9:42:53 PM:   │ │   └─┬ uid-safe@1.1.0
9:42:53 PM:   │ │     ├── base64-url@1.2.1
9:42:53 PM:   │ │     └── native-or-bluebird@1.1.2
9:42:53 PM:   │ ├─┬ debug@1.0.2
9:42:53 PM:   │ │ └── ms@0.6.2
9:42:53 PM:   │ ├── depd@0.3.0
9:42:53 PM:   │ ├─┬ errorhandler@1.1.1
9:42:53 PM:   │ │ └── escape-html@1.0.1
9:42:53 PM:   │ ├─┬ express-session@1.5.2
9:42:53 PM:   │ │ ├── buffer-crc32@0.2.3
9:42:53 PM:   │ │ ├─┬ uid-safe@1.0.1
9:42:53 PM:   │ │ │ └─┬ mz@1.3.0
9:42:53 PM:   │ │ │   ├─┬ thenify@3.3.1
9:42:53 PM:   │ │ │   │ └── any-promise@1.3.0
9:42:53 PM:   │ │ │   └── thenify-all@1.6.0
9:42:53 PM:   │ │ └── utils-merge@1.0.0
9:42:53 PM:   │ ├── finalhandler@0.0.2
9:42:53 PM:   │ ├── fresh@0.2.2
9:42:53 PM:   │ ├── media-typer@0.2.0
9:42:53 PM:   │ ├─┬ method-override@2.0.2
9:42:53 PM:   │ │ ├── methods@1.0.1
9:42:53 PM:   │ │ └── vary@0.1.0
9:42:53 PM:   │ ├── morgan@1.1.1
9:42:53 PM:   │ ├─┬ multiparty@3.2.9
9:42:53 PM:   │ │ ├─┬ readable-stream@1.1.14
9:42:53 PM:   │ │ │ ├── core-util-is@1.0.2
9:42:53 PM:   │ │ │ ├── isarray@0.0.1
9:42:53 PM:   │ │ │ └── string_decoder@0.10.31
9:42:53 PM:   │ │ └── stream-counter@0.2.0
9:42:53 PM:   │ ├── on-headers@0.0.0
9:42:53 PM:   │ ├── parseurl@1.0.1
9:42:53 PM:   │ ├── pause@0.0.1
9:42:53 PM:   │ ├── qs@0.6.6
9:42:53 PM:   │ ├── response-time@2.0.0
9:42:53 PM:   │ ├─┬ serve-favicon@2.0.1
9:42:53 PM:   │ │ └── fresh@0.2.2
9:42:53 PM:   │ ├─┬ serve-index@1.1.6
9:42:53 PM:   │ │ ├── batch@0.5.1
9:42:53 PM:   │ │ └── parseurl@1.3.3
9:42:53 PM:   │ ├─┬ serve-static@1.2.3
9:42:53 PM:   │ │ └─┬ send@0.4.3
9:42:53 PM:   │ │   ├─┬ finished@1.2.2
9:42:53 PM:   │ │   │ └── ee-first@1.0.3
9:42:53 PM:   │ │   ├── fresh@0.2.2
9:42:53 PM:   │ │   └── range-parser@1.0.3
9:42:53 PM:   │ ├── type-is@1.3.2
9:42:53 PM:   │ └── vhost@2.0.0
9:42:53 PM:   ├── cssmin@0.4.3
9:42:53 PM:   ├── fresh@0.5.2
9:42:53 PM:   ├─┬ fstream@1.0.12
9:42:53 PM:   │ ├── graceful-fs@4.2.8
9:42:53 PM:   │ ├── inherits@2.0.4
9:42:53 PM:   │ ├─┬ mkdirp@0.5.5
9:42:53 PM:   │ │ └── minimist@1.2.5
9:42:53 PM:   │ └─┬ rimraf@2.7.1
9:42:53 PM:   │   └─┬ glob@7.1.7
9:42:53 PM:   │     ├── fs.realpath@1.0.0
9:42:53 PM:   │     ├── inflight@1.0.6
9:42:53 PM:   │     ├─┬ minimatch@3.0.4
9:42:53 PM:   │     │ └─┬ brace-expansion@1.1.11
9:42:53 PM:   │     │   ├── balanced-match@1.0.2
9:42:53 PM:   │     │   └── concat-map@0.0.1
9:42:53 PM:   │     └── path-is-absolute@1.0.1
9:42:53 PM:   ├── http-accept@0.1.6
9:42:53 PM:   ├─┬ knox@0.9.2
9:42:53 PM:   │ ├─┬ once@1.4.0
9:42:53 PM:   │ │ └── wrappy@1.0.2
9:42:53 PM:   │ ├── stream-counter@1.0.0
9:42:53 PM:   │ └─┬ xml2js@0.4.23
9:42:53 PM:   │   ├── sax@1.2.4
9:42:53 PM:   │   └── xmlbuilder@11.0.1
9:42:53 PM:   ├─┬ less@4.1.1
9:42:53 PM:   │ ├─┬ copy-anything@2.0.3
9:42:53 PM:   │ │ └── is-what@3.14.1
9:42:53 PM:   │ ├─┬ errno@0.1.8
9:42:53 PM:   │ │ └── prr@1.0.1
9:42:53 PM:   │ ├── image-size@0.5.5
9:42:53 PM:   │ ├─┬ make-dir@2.1.0
9:42:53 PM:   │ │ ├── pify@4.0.1
9:42:53 PM:   │ │ └── semver@5.7.1
9:42:53 PM:   │ ├── mime@1.6.0
9:42:53 PM:   │ ├─┬ needle@2.9.0
9:42:53 PM:   │ │ ├─┬ debug@3.2.7
9:42:53 PM:   │ │ │ └── ms@2.1.3
9:42:53 PM:   │ │ └─┬ iconv-lite@0.4.24
9:42:53 PM:   │ │   └── safer-buffer@2.1.2
9:42:53 PM:   │ ├── parse-node-version@1.0.1
9:42:53 PM:   │ ├── source-map@0.6.1
9:42:53 PM:   │ └── tslib@1.14.1
9:42:53 PM:   ├── marked@3.0.2
9:42:53 PM:   ├── mime@1.2.11
9:42:53 PM:   ├── mustache@0.7.3
9:42:53 PM:   ├── uglify-js@3.14.1
9:42:53 PM:   └── underscore@1.13.1
9:42:53 PM: NPM modules installed
9:42:54 PM: Started restoring cached go cache
9:42:54 PM: Finished restoring cached go cache
9:42:54 PM: Installing Go version 1.10
9:42:59 PM: unset GOOS;
9:42:59 PM: unset GOARCH;
9:42:59 PM: export GOROOT='/opt/buildhome/.gimme_cache/versions/go1.10.linux.amd64';
9:42:59 PM: export PATH="/opt/buildhome/.gimme_cache/versions/go1.10.linux.amd64/bin:${PATH}";
9:42:59 PM: go version >&2;
9:42:59 PM: export GIMME_ENV="/opt/buildhome/.gimme_cache/env/go1.10.linux.amd64.env"
9:42:59 PM: go version go1.10 linux/amd64
9:42:59 PM: Installing missing commands
9:42:59 PM: Verify run directory
9:42:59 PM: Executing user command: make
9:42:59 PM: npm install
9:43:01 PM: node bin/newevents.js
9:43:02 PM: /opt/build/repo/node_modules/.bin/punch g
9:43:02 PM: Generating site...
9:43:02 PM: /opt/build/repo/node_modules/needle/lib/needle.js:618
9:43:02 PM:     stream.pipeline.apply(null, [resp].concat(pipeline).concat(pipelineCb));
9:43:02 PM:                    ^
9:43:02 PM: TypeError: Cannot read property 'apply' of undefined
9:43:02 PM:     at ClientRequest.<anonymous> (/opt/build/repo/node_modules/needle/lib/needle.js:618:20)
9:43:02 PM:     at ClientRequest.g (events.js:292:16)
9:43:02 PM:     at emitOne (events.js:96:13)
9:43:02 PM:     at ClientRequest.emit (events.js:188:7)
9:43:02 PM:     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:488:21)
9:43:02 PM:     at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
9:43:02 PM:     at TLSSocket.socketOnData (_http_client.js:377:20)
9:43:02 PM:     at emitOne (events.js:96:13)
9:43:02 PM:     at TLSSocket.emit (events.js:188:7)
9:43:02 PM:     at readableAddChunk (_stream_readable.js:176:18)
9:43:02 PM:     at TLSSocket.Readable.push (_stream_readable.js:134:10)
9:43:02 PM:     at TLSWrap.onread (net.js:559:20)
9:43:02 PM: make: *** [all] Error 1
9:43:02 PM: Skipping functions preparation step: no functions directory set
9:43:02 PM: Caching artifacts
9:43:02 PM: Started saving node modules
9:43:02 PM: Finished saving node modules
9:43:02 PM: Started saving pip cache
9:43:02 PM: Finished saving pip cache
9:43:02 PM: Started saving emacs cask dependencies
9:43:02 PM: Finished saving emacs cask dependencies
9:43:02 PM: Started saving maven dependencies
9:43:02 PM: Finished saving maven dependencies
9:43:02 PM: Started saving boot dependencies
9:43:02 PM: Finished saving boot dependencies
9:43:02 PM: Started saving go dependencies
9:43:04 PM: Finished saving go dependencies
9:43:07 PM: Error running command: Build script returned non-zero exit code: 2
9:43:07 PM: Failing build: Failed to build site
9:43:07 PM: failed during stage 'building site': Build script returned non-zero exit code: 2
9:43:07 PM: Finished processing build request in 34.639240641s
```

**Comment by valentine** [comment]
We will be immediately deprecating Punch and moving to [11ty](https://www.11ty.dev/) (which I've had a prototype HSG site of for ages) as a stopgap until a new site is developed.

**Comment by valentine** [comment]
Somehow works with Cloudflare Pages, so we've moved the site there for now.

**Comment by valentine** [comment]
[Cloudflare Pages Redirects](https://developers.cloudflare.com/pages/platform/redirects) do not support some of the features of [Netlify Redirects](https://docs.netlify.com/routing/redirects/) that we've been using, most notably wildcards/splat and forced redirects.

**Comment by kaihendry** [comment]
Perhaps consider the statically built hugo to escape the fragility of nodejs and npm churn?

**Comment by elfgoh** [comment]
I take it that migration to a new static site generator is still required? Is there a public call for volunteers in our comms channels?

**Comment by adithyaakrishna** [comment]
@valentine how about if we use docusaurus? 👀
